server:
  port: 8081
  servlet:
    session:
      timeout: PT2S
spring:
  redis:
    host: 106.12.95.66
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.95.66:3306/mysql?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: pbszcjdgb
  ldap:
    embedded:
      ldif: 'classpath:test-server.ldif'
      base-dn: dc=springframework,dc=org
      port: 8389
